### ISSUE TITLE
RSeQC terminology

### ISSUE THREAD

**Issue by rsuchecki** [ewels/nf-core-RNAseq#19]
Great work, I might be extending or at least re-purposing some of it soon. Just a comment about the RSeQC results in [output.md](https://github.com/ewels/nf-core-RNAseq/blob/master/docs/output.md#rseqc): inner distance should not be confused with insert size. See [here](http://thegenomefactory.blogspot.com.au/2013/08/paired-end-read-confusion-library.html) for disambiguation by @tseemann, parly quoted below. One might of course argue it is a local variable which can be called as one pleases ;-)

## Mind the gap (by @tseemann)

There is a lot of confusion about the gap of unknown bases. You will encounter terms like "insert size", "fragment size", "library size" and variations thereof. The term "insert" comes from a time before NGS existed, when cloning DNA in E.coli vectors was standard business.
```
PE reads      R1--------->                    <---------R2
fragment     ~~~========================================~~~
insert          ========================================
inner mate                ....................
```
The main confusion is with "insert size". The name itself suggests it is the unknown gap because it is "inserted" between R1 and R2, but this is misleading. It is more accurate to think of the insert as the piece of DNA inserted between the adaptors which enable amplification and sequencing of that piece of DNA. So the "insert" actually encompasses R1 and R2 as well as the unknown gap between them. The name for the gap itself is better named "inner mate distance" because it is self-descriptive and can vary depending on what read lengths you sequenced a DNA library with.

**Comment by ewels** [comment]
Thanks @rsuchecki! This is just my development fork, so I've moved your issue to the main repo. We can continue this there.. 👍
