### ISSUE TITLE
minimal alignment length --min_aln_length 

### ISSUE THREAD

**Issue by ivyyqu** [ewels/nf-core-rnaseq#26]
I cannot find any params for this --min_aln_length, and neither in STAR manual. Does is get actually pass on the workflow? is it the same param as the  --outFilterMatchNmin 20 for STAR? Thanks

**Comment by ewels** [comment]
Hi @ivyyqu,

This is my development fork of the main pipeline - in the future, please make issues there: https://github.com/nf-core/rnaseq

But in answer to your question, yes you're right - the `--min_aln_length` option was removed soon after it was added but we missed the documentation. So it is not passed on to the workflow, no. This came up the other day and I've already submitted a pull request to remove those docs: https://github.com/nf-core/rnaseq/pull/120

I hope that helps! Let me know if you have any other questions.

Phil
